# Generated by Django 4.2.23 on 2025-08-13 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='testdrive',
            constraint=models.UniqueConstraint(fields=('car', 'start_at'), name='unique_car_start'),
        ),
    ]
