# Generated by Django 4.2.23 on 2025-08-13 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('total_sales_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
