# Generated by Django 4.2.23 on 2025-08-13 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('FINANCING', 'Financing'), ('BANK_TRANSFER', 'Bank transfer'), ('OTHER', 'Other')], max_length=20)),
                ('sale_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract_number', models.CharField(blank=True, max_length=64)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='cars.car')),
            ],
            options={
                'ordering': ['-sale_datetime'],
            },
        ),
    ]
