# Generated by Django 4.2.23 on 2025-08-13 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='commission',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('sale', 'salesperson'), name='unique_sale_salesperson_commission'),
        ),
    ]
