# Generated by Django 4.2.23 on 2025-08-13 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=32, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=16)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('CVT', 'CVT'), ('DUAL_CLUTCH', 'Dual-clutch')], max_length=16)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('body_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('WAGON', 'Wagon'), ('VAN', 'Van'), ('PICKUP', 'Pickup'), ('OTHER', 'Other')], max_length=16)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drive_type', models.CharField(blank=True, choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', 'AWD'), ('4WD', '4WD')], max_length=8)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('REMOVED', 'Removed')], default='AVAILABLE', max_length=12)),
                ('location', models.CharField(choices=[('SHOWROOM', 'Showroom'), ('WAREHOUSE', 'Warehouse')], default='SHOWROOM', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['vin'], name='cars_car_vin_93daa8_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model', 'year'], name='cars_car_make_0aabde_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status'], name='cars_car_status_3b4442_idx'),
        ),
    ]
